version: "3"
services:
  server:
    image: demo
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/zapicito?useSSL=false
    networks:
      - demomysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: arm64v8/mysql:oracle
    networks:
      - demomysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=zapicito
      - MYSQL_USER=zapicito
      - MYSQL_PASSWORD=1234

networks:
  demomysql-net: