server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/zapicito
    url: jdbc:mysql://zapicito-db:3306/zapicito
    #username: ${MYSQL_USERNAME:root}
    username: zapicito
    #password: ${MYSQL_PASSWORD:12345678}
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create
        show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
